feat:Bottom-tab 구성
DDD-Community/quickly-frontend pull request #8
Opened 2022-07-19 16:54 UTC by SangchoKim

### 무엇을 한 것인지?
- bottom-tab 구성 
- svg 타입 정의 
- svg 아이콘 적용

### 중점적으로 확인해 주었으면 하는 부분
- 현재 작업중에 있습니다.

2022-07-23 01:57 UTC, nimuseel requested changes
@SangchoKim 

적용 화면이 보고 싶은데 스크린샷을 올려주실 수 있으실까요~?

2022-08-04 03:55 UTC, SangchoKim commented
@nimuseel 

bottom-tab 구성 완료하였고, 스크린샷 올려드립니다.

2022-08-07 08:27 UTC, nimuseel approved these changes
코멘트 하나만 확인 부탁드립니다~

추가로, PR 변경 사항이 너무 많아서 보기 힘든 부분이 있는 것 같아요. 쪼개서 올려주시면 리뷰하는 데 도움이 될 것 같습니다~

2022-08-07 08:27 UTC, nimuseel commented on metro.config.js
> +module.exports = (async () => {
@SangchoKim 

이 부분은 왜 수정되었는지 설명해주시면 좋을 것 같아요!

2022-08-07 13:46 UTC, SangchoKim commented on metro.config.js
> +module.exports = (async () => {
@nimuseel 

react-native에서 svg 파일을 사용할때 필요한 옵션입니다. 
react-native-svg-transformer 를 사용하려고 수정사항이 있었습니다.

2022-08-07 13:47 UTC, SangchoKim commented
@nimuseel 

네네 ~ 
좀 더 쪼개서 올려드릴께요~  피드백 감사합니다 :)

2022-08-07 13:47 UTC, merged