feat: 라벨 검색 layout 구성
DDD-Community/quickly-frontend pull request #9
Opened 2022-08-05 03:27 UTC by SangchoKim

### 무엇을 한 것인지?
라벨 인식 레이아웃 구성

### 중점적으로 확인해 주었으면 하는 부분
없습니다.

### 스크린샷(Optional)
![simulator_screenshot_44C325D5-DBD2-40C5-8F51-C3C2FB7D0C61](https://user-images.githubusercontent.com/36231361/182995176-a0172de0-80cd-4e34-8201-7a1f0916eaff.png)

2022-08-07 08:29 UTC, nimuseel requested changes
코멘트 몇 개 확인 부탁드립니다!

2022-08-07 08:29 UTC, nimuseel commented on src/components/AppLayout/types.ts
> +  styles?: any;
[확인]

RN StyleSheet에 대한 타입이 따로 있지 않을까요? 확인해보면 좋을 것 같아요~

2022-08-07 08:29 UTC, nimuseel commented on src/components/BottomTabBar/index.tsx
> +  console.log(state.index);
[적극]

console.log는 지우는 게 좋을 것 같아요.

2022-08-07 08:29 UTC, nimuseel commented on src/components/lds/BaseButton/styles.ts
> +  // marginHorizontal: 16,
[적극]

사용하지 않는 코드는 제거하는 게 좋을 것 같습니다~

commit history로 나중에 추가할 때 참고하면 좋을 것 같아요.

2022-08-07 13:48 UTC, SangchoKim commented on src/components/AppLayout/types.ts
> +  styles?: any;
확인해볼께요 ~~

2022-08-07 13:49 UTC, SangchoKim commented on src/components/BottomTabBar/index.tsx
> +  console.log(state.index);
네넹 ~ 알겠습니다.

2022-08-07 13:49 UTC, SangchoKim commented on src/components/lds/BaseButton/styles.ts
> +  // marginHorizontal: 16,
네넹 ~ 알겠습니다.

2022-08-13 03:58 UTC, nimuseel approved these changes
LGTM

2022-08-18 12:05 UTC, merged